services:
  web:
    build: 
      context: ./deadlockbp
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./deadlockbp/:/app
    ports:
      - "8000:8000"